Repository elmyossi/3DFinalProject, pull requests merged in 2018-12, with the labels that each got.

#1 check
  .idea/vcs.xml
  CMakeLists.txt
  LICENSE
  README.md
  cmake/FindLIBIGL.cmake
  main.cpp
Labels: enhancement

#2 edit readme file
  README.md
Labels: good first issue

#3 fix compilation to allow gui
  CMakeLists.txt
  main.cpp
Labels: enhancement

#7 added argmin center of japSphere. not working good yet.
  CMakeLists.txt
  src/JapSphere/jaapSphere.cpp
  src/JapSphere/jaapSphere.h
  src/main.cpp
Labels: bug

#8 display Inner Points
  src/main.cpp
Labels: enhancement

#9 - read number of lines in file and initiate correct mesh matrix
  src/JapSphere/jaapSphere.cpp
  src/JapSphere/jaapSphere.h
  src/main.cpp
Labels: enhancement
